### PR TITLE
Updated LEISR json to fix bug introduced (tree not saved) from earlie…

### PR DESCRIPTION
**Pull request by sjspielman**
…r json additions

### CODE REVIEW

**Comment by sjspielman** [comment]
EDIT: Not totally fixed. Wait for confirm..

**Comment by sjspielman** [comment]
Got it right this time, thanks!

**Comment by stevenweaver** [comment]
Hi Stephanie, 

It looks like the commit broke the LEISR unit test on travis. Can you check to see if it is a false positive?

https://travis-ci.org/veg/hyphy/builds/299374287?utm_source=github_status&utm_medium=notification

```
Input alignment description
Loaded **15** sequences, **10** sites, and **1** partitions from `/home/travis/build/veg/hyphy/tests/hbltests/libv3/data/dat.nuc`
Obtaining alignment-wide branch-length estimates
>Fitted an alignment-wide model. **Log-L = -10000000**.
Error:
'^parameter' is not an allowed argument type  in call to GetString(
Function call stack
1 : Get string -1 from object:^parameter. Store result in info
	Standard input redirect:
		Empty Associative List-------
2 : Branch under condition 'parameters.IsIndependent(models.generic.SetBranchLength.bl.p)'
	to
		<END EXECUTION>
	else
		<END EXECUTION>
	Standard input redirect:
		Empty Associative List-------
3 : A return statement with:1
	Standard input redirect:
		Empty Associative List-------
4 : estimators.ApplyExistingEstimates.df_correction+=estimators.applyBranchLength(_tree_name,_branch_name,model_descriptions[estimators.ApplyExistingEstimates.map[_branch_name]],_set_branch_length_to)
	Standard input redirect:
		Empty Associative List-------
5 : estimators.ApplyExistingEstimates("leisr.site_likelihood",leisr.site_model_mapping,leisr.alignment_wide_MLES,{"0":leisr.site_model_scaler_name})
	Standard input redirect:
		Empty Associative List-------
6 : LoadFunctionLibrary from file"LEISR.bf" using basepath /home/travis/build/veg/hyphy/tests/hbltests/libv3/. reading input from {"0":PATH_TO_CURRENT_BF+"data/dat.nuc","1":"Y","2":"Nucleotide","3":"GTR","4":"Gamma"}
-------
Check errors.log for details on execution errors.
Check messages.log details of this run.
/home/travis/.travis/job_stages: line 57:  5642 Segmentation fault      (core dumped) ./HYPHYMP LIBPATH=`pwd`/res/ $METHOD_TEST
```

Best,
Steven

**Comment by sjspielman** [comment]
Error is real, looking into it.

**Pull request merged**
