### PR TITLE
Updates GARD to print rateMatrix, among other data, to new JSON file

### PR DESCRIPTION
**Pull request by stevenweaver**
Once it passes review, we can "squash and merge" this PR.

### CODE REVIEW

**Comment by stevenweaver** [comment]
Sample JSON  with 1 partition.
```
{
 "rateMatrix":{
  {-0.9045850428096406, 0.1621073345600251, 0.5487665189402547, 0.1937111893093607}
  {0.3143089833030943, -1.027802500504365, 0.2119502298612162, 0.5015432873400548}
  {0.81378655145517, 0.1621073345600251, -1.169605075324556, 0.1937111893093607}
  {0.3143089833030943, 0.4197168256879841, 0.2119502298612162, -0.9459760388522945}
  },  
 "input":{
   "file name":"/home/sweaver/programming/hyphy/tests/hbltests/data/CD2.nex",
   "number of sequences":10,
   "number of sites":561,
   "partition count":2
  },  
 "timeElapsed":1509386280,
 "rvChoice":0,
 "rvRates":0
}
```

**Comment by stevenweaver** [comment]
Sample JSON with 2 or more partitions:

```

 "rateMatrix":{
  {-0.9100368013302654, 0.1115809831339299, 0.6577424640502665, 0.1407133541460689}
  {0.2057484125017314, -1.019985047987181, 0.1365777914608884, 0.677658844024561}
  {0.9908599807170966, 0.1115809831339299, -1.243154317997095, 0.1407133541460689}
  {0.2057484125017314, 0.5373607963830586, 0.1365777914608884, -0.8796870003456785}
  },
 "input":{
   "file name":"/home/sweaver/Flu.fasta",
   "number of sequences":21,
   "number of sites":1698,
   "partition count":3
  },
 "timeElapsed":1509385983,
 "rvChoice":0,
 "rvRates":0,
 "likelihoodScores":{
  {-1520.839063838499, -1578.768471767294, 0}
  {-1595.853629582311, -1419.093755515131, -1634.173485535962}
  {0, -1341.975356188352, -1303.3071589356}
  },
 "pairwiseP":{
  {0, 0.0008, 0}
  {0.0001, 0, 0.0001}
  {0, 0.0048, 0}
  },
 "singleTreeAICc":8925.004815220791
} 
```

**Comment by stephenshank** [comment]
This runs on my machine and gives the desired output. My only concern is the `timeElapsed` field, which was previously in seconds. Any idea what units it is currently in?

**Comment by stevenweaver** [comment]
Nice catch. I placed the wrong variable in timeElapsed. One moment.

**Pull request merged**
