### PR TITLE
RELrates renamed to LEISR 

### PR DESCRIPTION
**Pull request by sjspielman**
Avoids confusion with actual REL methods.

### CODE REVIEW

**Comment by stevenweaver** [comment]
Hi Stephanie, 

The dataset used by the ProteinFitGTR test causes travis.ci to kill the test due to running out of memory. Is it possible to find an alternative?

Best,
Steven

**Comment by sjspielman** [comment]
Ok, I will reduce the data set size and commit shortly. I hope this will work. The analysis takes an extremely long time in the first place, and it's possible that smaller datasets will just cause more convergence problems and make it slower. Stay tuned for commit and we'll see.

**Comment by stevenweaver** [comment]
Thank you. Maybe the error being thrown is a red herring. @stephenshank and I can investigate. It could be an issue specific to gcc. 

https://travis-ci.org/veg/hyphy/jobs/288766700

**Comment by stevenweaver** [comment]
Hi Stephanie, 
I've confirmed that the issue with ProteinGTRFit is with gcc. The issue occurs as soon as the batch file starts Phase 2. 

```
[PHASE 2] Performing initial REV fit to the data

### Fitting the REV model using constrained branch lengths proportions (REV-Phase-0)
Current Max: -5843.221      (0 % done) LF Evals/Sec: 247.9   CPU Load: 1.991   Error:
Memory Full Exiting...

Function call stack
1 : Optimize storing into, mles, the following likelihood function:likelihoodFunction ;
        Standard input redirect:
                Empty Associative List-------
```

**Comment by sjspielman** [comment]
Hi Steven,
Can you clarify what time means, as in, do I need to provide different test data? Thanks.

**Comment by stevenweaver** [comment]
No. 

While the smaller dataset will prove useful, the issue here is that the batch file performs differently when using a hyphy executable that is compiled with gcc vs. with clang. Namely, that ProteinGTRFit fails when using with a version of hyphy that has been compiled with the former.

**Comment by sjspielman** [comment]
Interesting.. I always use either gcc-6 or gcc-7, so on my end I haven't experienced failures with gcc.

**Comment by spond** [comment]
Dear @sjspielman and @stevenweaver,

This might be an `long` to `unsigned long` conversion issue, where something like this

```
malloc (something that evaluates to -1) 
```
gets called.  Clearly. this call should not be occurring, but I would look for evidence of such an issue in the code.

Best,
Sergei

**Comment by stevenweaver** [comment]
Thank you @spond, 
I will investigate shortly. The failure occurs in both Ubuntu and CentOS environments. Information about travis builds are found in the logs. 

```
Build system information
Build language: c\+\+
Build group: stable
Build dist: trusty
Build id: 288746292
Job id: 288746302
Runtime kernel version: 4.11.6-041106-generic
travis-build version: b304606a3
Build image provisioning date and time
Tue Aug 29 02:50:02 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

Best,
Steven

**Comment by sjspielman** [comment]
Hi everyone, 

Protein fitter code has been removed (I have placed it in local branch in my fork). Hopefully this helps.

-Stephanie

**Comment by stevenweaver** [comment]
Commit in this PR were merged and committed and in #676

**Pull request closed without merging**
