### PR TITLE
Code Cleanup

### PR DESCRIPTION
**Pull request by rdvelazquez**
Helping clean up the code base by removing old/unused files and folders. The repo is tracked by git so nothing is deleted permanently. Reducing the amount of old/unused code should help with development and maintenance, especially for people newer to the codebase like myself.

@spond and/or @stevenweaver Could you take a quick look at this?

__Proposed for deletion in this PR:__
- `./CMakeWin32/` not maintained anymore
    - Only had `CMakeLists.txt`
- `./conf/` not used anywhere
    - Only had `travis-install-mpi.sh`
- `./help/` because they are out of date and replaced by hyphy.org
    - `SelectionAnalyses.pdf`
    - `GettingStartedWithHyphy.pdf`
    - `Commands/`
- `./scripts/` not used anymore
- `./run_tests.sh` replaced by travis; not used anymore
- __@srwis has gone through the res directory and removed unused files (#952)__~~`./res/data/` not used anywhere~~
- ~~Old GUI files from the `./res/` directory:~~
    - ~~`./res/DatapanelAddins/`~~
    - ~~`./res/ChartAddins/`~~
    - ~~`./res/TreeAddins/`~~
    - ~~`./res/TemplateBatchFiles/gui/`~~
- __Based on @spond 's comment about the tests, I'm not deleting any of the tests for now.__ ~~Old tests (ideally, all tests that can be should be run as part of the continuous integration Travis build; I didn't go as far as to delete every test that is not part of the Travis build but we may want to consider this in the future {i.e. either adding the test to CI or removing it from the repo})~~:
    - ~~`./tests/hbltests/HMM/` 8 years old, don't seem to work with new hyphy~~
    - ~~`./tests/hbltests/BFFeatures/` 3 - 8 years old~~
    - ~~`./tests/hbltests/UnitTests/HBLCommands/testdata/Chinook_Sqlite.sqlite` I don't see it used anywhere~~
    - ~~`./tests/hbltests/Trickier/NonReversibleWithDynamicFrequencies.bf` Old, not used, and doesn't work~~

__I wasn't sure about these so I didn't delete them in this PR...:__
- `./src/lib/` I don’t think this is used anymore
- `./src/ocl/` I don’t think this is used anymore
- `./Contrib/` I don't think this is used anymore
- `./Examples/` They seem to be old files {at least 5 years old} but may still be useful for people to reference...

### CODE REVIEW

**Comment by spond** [comment]
Dear @rdvelazquez,

Let me review `hbltests`. Some of the files you mention test the features that **should** still be supported.

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @rdvelazquez,

> ./help/ because they are out of date and replaced by hyphy.org

`SelectionAnalyses.pdf` and `Getting Started with HyPhy.pdf` are both well-written and have no immediate analog on hyphy.org that I am aware of. Half of `SelectionAnalyses.pdf` is theory and is hardly out of date. 

Placing the pdfs prominently on the site and updating seems appropriate. It may also be appropriate to package the markdown on hyphy.org with HyPhy through a git subtree. 

As far as `travis-install-mpi.sh` goes,  testing the `MPI` target with travis would be prudent, but the task has not been completed and therefore we are not making use of the shell script at this time.

Best,
Steven

**Comment by rdvelazquez** [comment]
Thanks @stevenweaver. 

`SelectionAnalyses.pdf` is already available on hyphy.org in the [resources section](http://hyphy.org/resources/): http://hyphy.org/resources/hyphybook2007.pdf. I'm adding `Getting Started with HyPhy.pdf` to hyphy.org with this [PR](https://github.com/veg/hyphy-site/pull/60) to hyphy-site. Good suggestion.

**Comment by rdvelazquez** [comment]
@spond: Your comment about the tests makes sense to me. I adjusted the PR so that no tests are deleted. We can revisit the tests later.

@stevenweaver: hyphy.org will now have everything that was in the `./help/` directory.

**Pull request merged**
