### PR TITLE
2.3.11 - rc

### PR DESCRIPTION
**Pull request by stevenweaver**

### CODE REVIEW

**Comment by stephenshank** [comment]
@stevenweaver LGTM :thumbsup:

**Comment by stephenshank** [comment]
@stevenweaver Upon further reflection, I believe we'd like to take out the following `console.log` statements:

https://github.com/veg/hyphy/blob/beta/res/TemplateBatchFiles/SelectionAnalyses/MEME.bf#L467
https://github.com/veg/hyphy/blob/beta/res/TemplateBatchFiles/SelectionAnalyses/MEME.bf#L483

as they disrupt the tabular markdown output.

**Comment by stevenweaver** [comment]
@stephenshank, 

Nice catch. We could probably use eslint to lint HBL. This way console.log would generate warnings on travis builds for us.

**Comment by stephenshank** [comment]
@spond The preceding two comments relate to #747.

**Comment by spond** [comment]
Dear @stevenweaver and @stephenshank 

Yes, please do take out both commented console.log statements. I have embarrassingly left debugging statements in my commit.

Best,
Sergei

**Pull request merged**
