### PR TITLE
Origin/sel an

### PR DESCRIPTION
**Pull request by srwis**
removing files referenced in #936

### CODE REVIEW

**Comment by srwis** [comment]
@rdvelazquez when I run the failing commands on the cluster version of this branch like:
`./HYPHYMP LIBPATH=/home/travis/build/veg/hyphy/res/ tests/hbltests/libv3/SLAC.wbf`
they work with no error. How do I troubleshoot them or does this mean they should be working with travis?

**Comment by rdvelazquez** [comment]
hmm... I would think that they should be working on travis as well then. I restarted the travis build and I'll try running them on my mac as another datapoint.

**Comment by rdvelazquez** [comment]
I get: 
```
### Performing joint maximum likelihood ancestral state reconstruction
Error:
Attempting to operate on an undefined value; this is probably the result of an earlier 'soft' error condition

Function call stack
1 :  Branch under condition 'slac.negative_p<=slac.pvalue'
        to
                utility.EnsureKey(slac.report_to_screen,slac.i);
        else
                Branch under condition 'slac.positive_p<=slac.pvalue'
        to
                utility.EnsureKey(slac.report_to_screen,slac.i);
        else
                Branch under condition 'None!=slac.print_row'
        to
                Branch under condition '!slac.printed_header_sampler'
        to
                io.ReportProgressMessageMD("slac","anc"+slac.i,"For partition "+(slac.i+1)+" these sites are significant at p <="+slac.pvalue+"\n");
        else
                fprintf(stdout, io.FormatTableRow(slac.print_row,slac.table_output_options));
        else
                slac.site+=1;

-------
2 :  LoadFunctionLibrary("SelectionAnalyses/SLAC.bf", /Users/ryanvelazquez/Documents/repos/hyphy/tests/hbltests/libv3/, {"--code":"Universal","--alignment":PATH_TO_CURRENT_BF+"data/CD2.nex","--branches":"All"});
-------
```

When running `./hyphy tests/hbltests/libv3/SLAC.wbf` on my mac. (from this branch)

Could it be that what is at your LIBPATH isn't updated with the most recent branch?

**Comment by rdvelazquez** [comment]
looks like it's not from code in this PR though:
https://travis-ci.org/veg/hyphy/jobs/518469462#L514 (That's a link the failing build of the current develop branch)
Go ahead and merge this in and we'll look at the SLAC issue separately.

**Pull request merged**
