### PR TITLE
increased max number of GA rate classes from 5 to 18

### PR DESCRIPTION
**Pull request by hverdonk**

### CODE REVIEW

**Comment by stevenweaver** [comment]
@hverdonk -- Would it be possible to provide reasoning to increase the max number?

**Comment by hverdonk** [comment]
I upped it locally to test the GA's stability with larger numbers of rate classes, and opened a pull request in case someone wanted to replicate my work whenever it gets published.

That said, I only tested up to 6 rate classes, and I don't think anyone would ever go beyond that in real life, so feel free to close this pull request without merging.

**Comment by stevenweaver** [comment]
OK, I increased it to 6 to match the maximum performed.

**Comment by hverdonk** [comment]
Perfect, thank you!

**Pull request merged**
