### PR TITLE
2.3.4

### PR DESCRIPTION
**Pull request by stevenweaver**

### CODE REVIEW

**Comment by spond** [comment]
Dear @stevenweaver,

Please review and create a release if you are comfortable doing so. 

Best,
Sergei

**Comment by stevenweaver** [comment]
The changes to output files breaks visualizations. We'll try to target the release for later this month.

**Comment by spond** [comment]
Dear @stevenweaver,

Sounds good. I'll have some forthcoming minor patches to the core, then. 

Best,
Sergei

**Comment by stevenweaver** [comment]
Accidentally performed a merge in the wrong direction. Fixing now.

**Comment by stevenweaver** [comment]
So in this release we have a

* New method :  ProteinGTRFit.bf
* New binary model
* Additions to JSON output
* Bug fixes

Is there anything else of note?

**Comment by sjspielman** [comment]
We also have a new DNA model (JC69), as well as implementations of relative rates analyses for protein and nucleotide data.

The ProteinGTRFit.bf is experimental and is very much not guaranteed to work for users (in fact it is only sometimes guaranteed to work for us..). To this end I am going to update the prompt to hide this analysis from users, because it is very much not ready for prime time. That commit is coming shortly.

I would really like to see if I can get +F amino acid models into this release (currently they are coded as a bad hack), but I'm not sure I will make the Friday cut. It's not urgent to be in this release, but it is used in the protein analyses. If we can set the release for end of business Friday, I can hustle and hopefully get it working by then. If not, it will be in next release.

**Pull request merged**
