### PR TITLE
moving MEME to kwargs

### PR DESCRIPTION
**Pull request by rdvelazquez**

### CODE REVIEW

**Comment by rdvelazquez** [comment]
@stephenshank this is ready for your review and input.

**Comment by stephenshank** [comment]
Dear @rdvelazquez,

Per our discussion, my main concern at the moment is that the `--output` flag did not work as expected. I could not get it to work for BUSTED either... @spond, any ideas?

Best,
Stephen

**Comment by spond** [comment]
Dear @stephenshank,

Since I didn't partake in the previous discussion, can you provide more details on the observed vs expected behavior?

Best,
Sergei

**Comment by stephenshank** [comment]
Dear @spond,

No JSON file is written to the value that follows `--output`. When I run
```
HYPHYMP busted --alignment CD2-slim.fasta --tree CD2.new --output result.json
```

there is no `result.json` in the working directory, with similar behavior for MEME. Though `Save the resulting JSON file to : result.json` does appear in the standard output. When this parameter is omitted, the old behavior (appending `.BUSTED.json` to the input file) still works fine.

Best,
Stephen

**Comment by spond** [comment]
Dear @stephenshank,

Ah, OK. When specified as a relative path, the file was being written out to the **analysis** directory (i.e. relative to `BUSTED.bf`), not relative to the `cwd`. I made changes to BUSTED.bf and IOFUnctions.bf to address this (see a66cce756e4b428543d2d8c95ac99a990f38e5eb)

A fix will require `MEME.bf` to call `io.PromptUserForFilePath` instead of `io.PromptUserForString` when asking for the JSON path.

Best,
Sergei

**Pull request merged**
